labels:
  - name: "Priority: Low"
    color: 009800
  - name: "Priority: Medium"
    color: fbca04
  - name: "Priority: High"
    color: eb6420
  - name: "Priority: Critical"
    color: e11d21
  - name: "Status: Planned"
    color: fef2c0
  - name: "Status: In Progress"
    color: cccccc
  - name: "Status: Review Needed"
    color: c2e0c6
  - name: "Type: Bug"
    color: d73a4a
  - name: "Type: Idea"
    color: 001494
  - name: "Type: Enhancement"
    color: 84b6eb
  - name: "Type: Question"
    color: d876e3
  - name: "good first issue"
    color: 7057ff
  - name: "greenkeeper"
    color: 00c775
  - name: "Help Wanted"
    color: 008672
